### ISSUE TITLE
Re-use a distilled student as a teacher

### ISSUE THREAD

**Issue by quoccuongpresent244** [DefangChen/SimKD#14]
Hi, I just have some problems here. I used the ShuffleV2_1_5 that was distilled from resnet32x4_vanilla on CIFAR-100, and now I want to use that result (ShuffleV2_1_5) as a teacher. But when I executed the code, the error shows up as follows. One noticeable thing is that the accuracy of the model is too low, why?

```
Use GPU: 0 for training
==> loading teacher model
==> done
Files already downloaded and verified
/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Files already downloaded and verified
/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Test: [0/313]	GPU: 0	Time: 1.615	Loss 4.6052	Acc@1 0.000	Acc@5 3.125
Test: [200/313]	GPU: 0	Time: 3.354	Loss 4.6052	Acc@1 0.964	Acc@5 5.193
teacher accuracy:  1.0
==> training...
Traceback (most recent call last):
  File "train_student.py", line 428, in <module>
    main()
  File "train_student.py", line 169, in main
    main_worker(None if ngpus_per_node > 1 else opt.gpu_id, ngpus_per_node, opt)
  File "train_student.py", line 365, in main_worker
    train_acc, train_acc_top5, train_loss = train(epoch, train_loader, module_list, criterion_list, optimizer, opt)
  File "/kaggle/working/SimKD/helper/loops.py", line 156, in train_distill
    trans_feat_s, trans_feat_t, pred_feat_s = module_list[1](feat_s[-2], feat_t[-2], cls_t)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/kaggle/working/SimKD/models/util.py", line 234, in forward
    pred_feat_s = cls_t(temp_feat)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/kaggle/working/SimKD/models/ShuffleNetv2.py", line 90, in forward
    out1 = self.bn1(self.conv1(x))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [64, 704]

```

**Comment by DefangChen** [comment]
What script did you use?

**Comment by quoccuongpresent244** [comment]
Here is the script
`!python train_student.py --path_t ./save/teachers/models/S:ShuffleV2_1_5_T:/ShuffleV2_1_5_best.pth --distill simkd --model_s ShuffleV2 -c 0 -d 0 -b 1 --trial 0`

**Comment by DefangChen** [comment]
Since the student classifier is not trained with our method, it is likely that the teacher accuracy will be at 1.0 (random guess) if you load the random initialized student classifier. 
If you intend to repurpose the previous student model (ShuffleV2_1_5) as a new teacher model, it is necessary to load the previous teacher classifier of ResNet32x4.

**Comment by quoccuongpresent244** [comment]
I also tried to train ShuffleNetV2_1_5 with the vanilla method (train_teacher.py). Then I used that as a teacher, and the same error occurred.

```
Use GPU: 0 for training
==> loading teacher model
==> done
Files already downloaded and verified
/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Files already downloaded and verified
/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Test: [0/313]	GPU: 0	Time: 1.522	Loss 1.2072	Acc@1 75.000	Acc@5 87.500
Test: [200/313]	GPU: 0	Time: 3.615	Loss 1.1096	Acc@1 73.678	Acc@5 91.853
teacher accuracy:  74.22
==> training...
Traceback (most recent call last):
  File "train_student.py", line 428, in <module>
    main()
  File "train_student.py", line 169, in main
    main_worker(None if ngpus_per_node > 1 else opt.gpu_id, ngpus_per_node, opt)
  File "train_student.py", line 365, in main_worker
    train_acc, train_acc_top5, train_loss = train(epoch, train_loader, module_list, criterion_list, optimizer, opt)
  File "/kaggle/working/SimKD/helper/loops.py", line 156, in train_distill
    trans_feat_s, trans_feat_t, pred_feat_s = module_list[1](feat_s[-2], feat_t[-2], cls_t)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/kaggle/working/SimKD/models/util.py", line 234, in forward
    pred_feat_s = cls_t(temp_feat)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/kaggle/working/SimKD/models/ShuffleNetv2.py", line 90, in forward
    out1 = self.bn1(self.conv1(x))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [64, 704]
```

**Comment by DefangChen** [comment]
This issue is most likely due to a dimension mismatch. You can print the shape of the dimensions involved to identify the source of the problem.

**Comment by Dk146** [comment]
I noticed that 32x4 resnet (as teacher) and ShuffleV2_1_5 (as student) got the best results. So why did you mention in the article and documentation that resnet 32x4 and resnet 8x4 have the best accuracy.

**Comment by DefangChen** [comment]
Please point out the specific sentence such that I could better clarify.

**Comment by mountains-high** [comment]
> Hi, I just have some problems here. I used the ShuffleV2_1_5 that was distilled from resnet32x4_vanilla on CIFAR-100, and now I want to use that result (ShuffleV2_1_5) as a teacher. But when I executed the code, the error shows up as follows. One noticeable thing is that the accuracy of the model is too low, why?
> 
> ```
> Use GPU: 0 for training
> ==> loading teacher model
> ==> done
> Files already downloaded and verified
> /opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
>   cpuset_checked))
> Files already downloaded and verified
> /opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
>   cpuset_checked))
> Test: [0/313]	GPU: 0	Time: 1.615	Loss 4.6052	Acc@1 0.000	Acc@5 3.125
> Test: [200/313]	GPU: 0	Time: 3.354	Loss 4.6052	Acc@1 0.964	Acc@5 5.193
> teacher accuracy:  1.0
> ==> training...
> Traceback (most recent call last):
>   File "train_student.py", line 428, in <module>
>     main()
>   File "train_student.py", line 169, in main
>     main_worker(None if ngpus_per_node > 1 else opt.gpu_id, ngpus_per_node, opt)
>   File "train_student.py", line 365, in main_worker
>     train_acc, train_acc_top5, train_loss = train(epoch, train_loader, module_list, criterion_list, optimizer, opt)
>   File "/kaggle/working/SimKD/helper/loops.py", line 156, in train_distill
>     trans_feat_s, trans_feat_t, pred_feat_s = module_list[1](feat_s[-2], feat_t[-2], cls_t)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/kaggle/working/SimKD/models/util.py", line 234, in forward
>     pred_feat_s = cls_t(temp_feat)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
>     input = module(input)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/kaggle/working/SimKD/models/ShuffleNetv2.py", line 90, in forward
>     out1 = self.bn1(self.conv1(x))
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [64, 704]
> ```

Hi @DefangChen,

I encountered a similar error when I tried to test from wrn_40_2 to wrn_40_1, --> wrn_16_2, ShuffleNetV2. Could you please help me solve the error? I checked the shape, and it was indeed 4D.
```"teacher accuracy:  75.61
==> training...
Traceback (most recent call last):
  File "train_student.py", line 440, in <module>
    main()
  File "train_student.py", line 170, in main
    main_worker(None if ngpus_per_node > 1 else opt.gpu_id, ngpus_per_node, opt)
  File "train_student.py", line 377, in main_worker
    train_acc, train_acc_top5, train_loss = train(epoch, train_loader, module_list, criterion_list, optimizer, opt)
  File "/home//cuda0_spr_org_SimKD/helper/loops.py", line 199, in train_distill
    trans_feat_s, trans_feat_t, pred_feat_s = module_list[1](feat_s[-2], feat_t[-2], cls_t)
  File "/home//miniconda3/envs/cmi/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//cuda0_spr_org_SimKD/models/util.py", line 492, in forward
    pred_feat_s = cls_t(temp_feat)
  File "/home//miniconda3/envs/cmi/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//cuda0_spr_org_SimKD/models/wrn.py", line 53, in forward
    return self.layer(x)
  File "/home//miniconda3/envs/cmi/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//miniconda3/envs/cmi/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home//miniconda3/envs/cmi/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//cuda0_spr_org_SimKD/models/wrn.py", line 31, in forward
    x = self.relu1(self.bn1(x))
  File "/home//miniconda3/envs/cmi/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home//miniconda3/envs/cmi/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 138, in forward
    self._check_input_dim(input)
  File "/home//miniconda3/envs/cmi/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 410, in _check_input_dim
    raise ValueError("expected 4D input (got {}D input)".format(input.dim()))
ValueError: expected 4D input (got 2D input)"
```
